name: CalorieCheck
description: 'Gerencie suas metas, seus ganhos e seus gastos de calorias diário, semanal, mensal e até mesmo anual.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.2
  flutter_riverpod: ^2.5.1
  bdd_widget_test: ^1.7.4
  build_runner: ^2.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - ./lib/src/assets/images/logo.png

flutter_icons:
  ios: true
  android: true
  image_path: './lib/src/assets/images/logo.png'